### ISSUE TITLE
処理無いなら削除しちゃいますか！

### ISSUE THREAD

**Issue by tomofumi-koyama** [boxing708/task_app#12]
https://github.com/boxing708/task_app/blob/0a388373c46033165523d1c9bf4a714028998e05/app/controllers/tasks_controller.rb#L38-L42

**Comment by boxing708** [comment]
ルーティングでeditアクションとassignアクションが呼ばれているので、消しちゃうと編集ページとアサインページにいけない気がしてます...

**Comment by tomofumi-koyama** [comment]
確認済み
