### ISSUE TITLE
set_userメソッドの処理に関して

### ISSUE THREAD

**Issue by tomofumi-koyama** [boxing708/task_app#14]
https://github.com/boxing708/task_app/blob/d07cec28a6449179d4a272f75b4388e501b27893/app/controllers/users_controller.rb#L10-L11

「def set_user」がshowしか使用されていないのであれば、showメソッドに処理を実装ですでも良いかなと思うのですがいかがでしょうか？

**Comment by boxing708** [comment]
今後他のアクションで使う可能性があるかなと思い、メソッド化していましたが現時点では必要ないですね！
