### ISSUE TITLE
「%{}」がある場合はダブルクォーテーション良いが、ない場合はダブルクォーテーションは不要

### ISSUE THREAD

**Issue by tomofumi-koyama** [boxing708/task_app#4]
https://github.com/boxing708/task_app/blob/0a388373c46033165523d1c9bf4a714028998e05/config/locales/ja.yml#L24

**Comment by tomofumi-koyama** [comment]
ファイル内の全体的な話です

**Comment by boxing708** [comment]
修正しました。
