### ISSUE TITLE
redirect_backとredirect_toの使い分けの違いについて

### ISSUE THREAD

**Issue by tomofumi-koyama** [boxing708/task_app#5]
https://github.com/boxing708/task_app/blob/0a388373c46033165523d1c9bf4a714028998e05/app/controllers/comments_controller.rb#L5

何か意図などありましたら教えてください。

**Comment by boxing708** [comment]
https://qiita.com/100010/items/3ae5dea25e85b0cbf1ee
大分前に書いたコードで忘れてしまっていたのですが、上記の記事に書いてあるようにRails5.1~ `redirect_to :back`だと怒られるみたいです

**Comment by tomofumi-koyama** [comment]
確認済み。closeします。
