### ISSUE TITLE
シングルクォーテーション対応

### ISSUE THREAD

**Issue by tomofumi-koyama** [boxing708/task_app#7]
https://github.com/boxing708/task_app/blob/0a388373c46033165523d1c9bf4a714028998e05/app/controllers/comments_controller.rb#L17

t("flash.xxxx”はシングルクォーテーションが良いかな。

**Comment by boxing708** [comment]
修正しました！
これは慣習的なものでしょうか？？
ダブルクオーテーションとシングルクオーテーションの使い分けについて明日お聞きしたいです！
